"use client";
import {useRef,useState,type FormEvent} from "react";
import {WorkerSidebar} from "@/components/worker-sidebar";
import {useAuth} from "@/components/auth-provider";
import {useVerification,verificationStateLabels} from "@/lib/use-verification";
import {apiFetch,ApiError} from "@/lib/api";
import {jobTimestamp} from "@/lib/worker-jobs";
const documents={AADHAAR:"Aadhaar",PAN:"PAN",DRIVING_LICENSE:"Driving Licence",VOTER_ID:"Voter ID"};
export default function VerificationPage(){
 const state=useVerification();const {refreshUser}=useAuth();const [type,setType]=useState<keyof typeof documents>("PAN");const [busy,setBusy]=useState(false);const submitting=useRef(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(submitting.current)return;const form=event.currentTarget,data=new FormData(form);for(const key of ["documentFront","documentBack"]){const file=data.get(key);if(file instanceof File&&!file.size){data.delete(key);continue;}if(file instanceof File&&(file.size>5*1024*1024||!["image/jpeg","image/png","application/pdf"].includes(file.type))){setError("Upload JPG, PNG or PDF files, no larger than 5 MB each.");return;}}
 submitting.current=true;setBusy(true);setError("");setMessage("");try{await apiFetch("/api/worker/verification",{method:"POST",body:data});form.reset();setMessage("Verification submitted successfully.");state.reload();await refreshUser(true);}catch(cause){setError(cause instanceof Error?cause.message:"Unable to submit verification. Please try again.");if(cause instanceof ApiError&&[403,409].includes(cause.status))state.reload();}finally{submitting.current=false;setBusy(false);}}
 const data=state.data;const editable=data&&["NOT_SUBMITTED","REJECTED"].includes(data.submissionState);
 return <div className="min-h-screen lg:grid lg:grid-cols-[240px_1fr]"><WorkerSidebar/><main className="min-w-0 px-5 py-8 sm:px-8"><div className="mx-auto max-w-3xl"><h1 className="text-3xl font-bold">Verification</h1><p className="mt-2 text-slate-600">Submit your details to verify your worker profile.</p>
 {message&&<p role="status" className="mt-5 rounded-lg bg-teal-50 p-4 text-teal-800">{message}</p>}{error&&<p role="alert" className="mt-5 rounded-lg bg-red-50 p-4 text-red-800">{error}</p>}
 {state.loading?<p role="status" className="mt-8">Loading verification...</p>:state.error?<div role="alert" className="mt-8 text-red-700">{state.error}<button onClick={state.reload} className="ml-3 underline">Retry</button></div>:data&&<><section className="mt-6 rounded-xl border bg-white p-6"><h2 className="text-xl font-semibold">Verification Status</h2><p className="mt-3 inline-block rounded-full bg-teal-50 px-3 py-1 font-semibold text-teal-800">{verificationStateLabels[data.submissionState]}</p><p className="mt-4 text-slate-600">{data.submissionState==="NOT_SUBMITTED"?"Complete verification before your profile can become available to customers.":data.submissionState==="PENDING_REVIEW"?"Your documents have been submitted and are waiting for review.":data.submissionState==="VERIFIED"?"Your worker profile has been verified.":data.submissionState==="REJECTED"?"Update your verification details and submit again.":"Your worker account verification has been suspended."}</p>{data.rejectionReason&&<p className="mt-3 whitespace-pre-wrap break-words">Reason: {data.rejectionReason}</p>}
 {data.verification&&<dl className="mt-5 space-y-3"><div><dt className="text-sm text-slate-500">Full Legal Name</dt><dd>{data.verification.fullLegalName}</dd></div><div><dt className="text-sm text-slate-500">Document Type</dt><dd>{documents[data.verification.documentType as keyof typeof documents]}</dd></div><div><dt className="text-sm text-slate-500">Masked Document Number</dt><dd>{data.verification.maskedDocumentNumber}</dd></div><div><dt className="text-sm text-slate-500">Submitted Date</dt><dd>{jobTimestamp(data.verification.submittedAt)}</dd></div><div><dt className="text-sm text-slate-500">Documents</dt><dd>Front submitted{data.verification.documents.back?"; back submitted":""}</dd></div></dl>}</section>
 {editable&&<form onSubmit={submit} className="mt-6 space-y-5 rounded-xl border bg-white p-6"><h2 className="text-xl font-semibold">{data.submissionState==="REJECTED"?"Resubmit Verification":"Verification Details"}</h2><p className="text-sm text-slate-500">Your document number is used for format validation. Only its last four characters are retained. Documents are stored privately.</p><div><label htmlFor="legal-name" className="block font-medium">Full Legal Name</label><input id="legal-name" name="fullLegalName" required minLength={2} maxLength={100} defaultValue={data.verification?.fullLegalName} disabled={busy} className="mt-2 w-full rounded-lg border p-3"/></div><div><label htmlFor="document-type" className="block font-medium">Document Type</label><select id="document-type" name="documentType" value={type} disabled={busy} onChange={event=>setType(event.target.value as keyof typeof documents)} className="mt-2 w-full rounded-lg border p-3">{Object.entries(documents).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div><div><label htmlFor="document-number" className="block font-medium">Document Number</label><input id="document-number" name="documentNumber" required maxLength={40} autoComplete="off" disabled={busy} className="mt-2 w-full rounded-lg border p-3"/></div>{["documentFront",...(type!=="PAN"?["documentBack"]:[])].map(key=><div key={key}><label htmlFor={key} className="block font-medium">{key==="documentFront"?"Front Document":"Back Document"}</label><input id={key} name={key} type="file" accept="image/jpeg,image/png,application/pdf" required disabled={busy} className="mt-2 block w-full text-sm"/><p className="mt-2 text-xs text-slate-500">JPG, PNG or PDF. Maximum 5 MB per file.</p></div>)}<button disabled={busy} className="rounded-lg bg-teal-700 px-5 py-3 font-semibold text-white disabled:opacity-50">{busy?"Submitting...":"Submit for Verification"}</button></form>}</>}
 </div></main></div>;
}
