import {test,mock} from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {randomUUID,randomBytes} from 'node:crypto';
import {readdir,access} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import jwt from 'jsonwebtoken';
const users=['WORKER','WORKER','CUSTOMER'].map(role=>({id:randomUUID(),name:'Test Account',phone:'0000000000',role,isActive:true}));
const [a,b,c]=users;let profiles=users.slice(0,2).map(user=>({id:randomUUID(),userId:user.id,user,verificationStatus:'PENDING',verificationSubmittedAt:null,verification:null})),fail=false,queue=Promise.resolve();
const matches=(row,where)=>Object.entries(where).every(([key,value])=>value instanceof Date?row[key]?.getTime()===value.getTime():value&&typeof value==='object'?matches(row[key],value):row[key]===value);
const db={user:{findUnique:async({where})=>users.find(u=>u.id===where.id)},workerProfile:{findFirst:async({where})=>structuredClone(profiles.find(p=>matches(p,where))??null),updateMany:async({where,data})=>{const rows=profiles.filter(p=>matches(p,where));rows.forEach(p=>Object.assign(p,data));return {count:rows.length};}},workerVerification:{upsert:async({where,create,update})=>{if(fail)throw Error('Private database information');const p=profiles.find(p=>p.id===where.workerId);p.verification={...(p.verification??create),...update};return p.verification;}},async $transaction(action){const previous=queue;let release;queue=new Promise(r=>release=r);await previous;const before=structuredClone(profiles);try{return await action(db);}catch(e){profiles=before;throw e;}finally{release();}}};
mock.module('../dist/lib/prisma.js',{namedExports:{getPrismaClient:()=>db}});process.env.JWT_SECRET=randomBytes(48).toString('hex');
const {default:app}=await import('../dist/app.js');const {cleanupVerificationFiles}=await import('../dist/services/storage.service.js');
const root=fileURLToPath(new URL('../uploads/verification/',import.meta.url));
const pdf=Buffer.from('%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\n%%EOF\n');
const form=(fields={},front=pdf,mime='application/pdf',filename='../../identity.pdf')=>{const f=new FormData();for(const [key,value]of Object.entries({fullLegalName:' Legal Name ',documentType:'PAN',documentNumber:'abcde1234f',...fields}))f.append(key,value);if(front)f.append('documentFront',new Blob([front],{type:mime}),filename);return f;};
test('private worker verification multipart/state/cleanup integration (database double, real local files)',async t=>{
 const server=app.listen(0,'127.0.0.1');await once(server,'listening');const url='http://127.0.0.1:'+server.address().port;const keys=new Set();t.after(async()=>{for(const p of profiles)for(const key of [p.verification?.documentFrontPath,p.verification?.documentBackPath])if(key)keys.add(key);await cleanupVerificationFiles([...keys]);await new Promise(resolve=>server.close(resolve));});
 const request=async(method='GET',body,user=a,path='/api/worker/verification')=>{const response=await fetch(url+path,{method,headers:user?{Authorization:'Bearer '+jwt.sign({userId:user.id,role:user.role},process.env.JWT_SECRET,{expiresIn:'1h'})}:{},body});return {status:response.status,body:await response.json()};};
 await t.test('only authenticated WORKER; GET own initial state, no public document URLs',async()=>{for(const method of ['GET','POST']){assert.equal((await request(method,undefined,null)).status,401);assert.equal((await request(method,undefined,c)).status,403);}const data=(await request()).body.data;assert.equal(data.submissionState,'NOT_SUBMITTED');assert.equal(data.verification,null);});
 await t.test('whitelist and format validation never permits self-approval or writes files',async()=>{for(const fields of [{verificationStatus:'VERIFIED',isVerified:'true',rating:'5',role:'ADMIN',workerId:b.id,userId:b.id,reviewedAt:'2099-01-01',rejectionReason:'forged'},{fullLegalName:' '},{documentType:'toString'},{documentNumber:'not-valid'},{documentType:'AADHAAR',documentNumber:'234567890123'}])assert.equal((await request('POST',form(fields))).status,400);assert.equal(profiles[0].verificationStatus,'PENDING');assert.equal(profiles[0].verification,null);});
 await t.test('content signatures, MIME, size, file count and unexpected fields are enforced',async()=>{
  assert.equal((await request('POST',form({},Buffer.from('<html>script</html>'),'application/pdf'))).status,400);
  assert.equal((await request('POST',form({},pdf,'image/png'))).status,400);assert.equal((await request('POST',form({},pdf,'application/pdf','unsafe.exe'))).status,400);
  assert.equal((await request('POST',form({},Buffer.alloc(5*1024*1024+1)))).status,400);
  const duplicate=form();duplicate.append('documentFront',new Blob([pdf],{type:'application/pdf'}),'second.pdf');assert.equal((await request('POST',duplicate)).status,400);
  const unknown=form();unknown.append('unexpected',new Blob([pdf],{type:'application/pdf'}),'other.pdf');assert.equal((await request('POST',unknown)).status,400);
 });
 await t.test('first submission persists private generated files, masked metadata and PENDING; repeated pending submission conflicts',async()=>{
  const result=await request('POST',form());assert.equal(result.status,201);assert.equal(result.body.data.submissionState,'PENDING_REVIEW');assert.ok(result.body.data.submittedAt);assert.equal(result.body.data.verification.maskedDocumentNumber,'XXXX 234F');assert.equal(profiles[0].verification.documentNumberLast4,'234F');assert.ok(!JSON.stringify(result.body).includes('ABCDE1234F'));assert.ok(!JSON.stringify(result.body).includes('documentFrontPath'));const key=profiles[0].verification.documentFrontPath;keys.add(key);assert.match(key,/^[0-9a-f-]{36}\.pdf$/);await access(root+key);assert.equal((await request('GET',undefined,null,'/uploads/verification/'+key)).status,404);assert.equal((await request('POST',form())).status,409);assert.equal((await request('GET',undefined,b)).body.data.verification,null);
 });
 await t.test('rejected resubmission replaces files after commit, clears review reason and returns Pending Review',async()=>{const p=profiles[0],old=p.verification.documentFrontPath;p.verificationStatus='REJECTED';p.verification.reviewedAt=new Date();p.verification.rejectionReason='Unreadable document';assert.equal((await request()).body.data.rejectionReason,'Unreadable document');const result=await request('POST',form({documentNumber:'ABCDE5678F'}));assert.equal(result.status,201);assert.equal(result.body.data.submissionState,'PENDING_REVIEW');assert.equal(result.body.data.rejectionReason,null);assert.equal(result.body.data.reviewedAt,null);assert.equal(profiles[0].verification.documentNumberLast4,'678F');keys.add(profiles[0].verification.documentFrontPath);await assert.rejects(access(root+old));});
 await t.test('VERIFIED and SUSPENDED cannot self-reset or replace documents',async()=>{const p=profiles[0],key=p.verification.documentFrontPath;for(const [status,code]of [['VERIFIED',409],['SUSPENDED',403]]){p.verificationStatus=status;assert.equal((await request()).body.data.submissionState,status);assert.equal((await request('POST',form())).status,code);assert.equal(p.verificationStatus,status);assert.equal(p.verification.documentFrontPath,key);}});
 await t.test('database failure rolls back state and cleans new files; simultaneous first submissions win once',async()=>{const before=(await readdir(root)).sort();fail=true;const error=await request('POST',form(),b);fail=false;assert.equal(error.status,500);assert.ok(!JSON.stringify(error.body).includes('Private'));assert.deepEqual((await readdir(root)).sort(),before);assert.equal(profiles[1].verificationSubmittedAt,null);const results=await Promise.all([request('POST',form(),b),request('POST',form(),b)]);assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);keys.add(profiles[1].verification.documentFrontPath);assert.equal((await request('GET',undefined,b)).body.data.submissionState,'PENDING_REVIEW');});
 await t.test('two-sided identity requires back and accepts real PNG/PDF content without storing a full Aadhaar number',async()=>{profiles[1].verificationStatus='REJECTED';const f=form({documentType:'AADHAAR',documentNumber:'234567890123'},Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a3X8AAAAASUVORK5CYII=','base64'),'image/png','front.png');f.append('documentBack',new Blob([pdf],{type:'application/pdf'}),'back.pdf');const result=await request('POST',f,b);assert.equal(result.status,201);assert.equal(result.body.data.verification.maskedDocumentNumber,'XXXX 0123');assert.ok(result.body.data.verification.documents.back);assert.ok(!JSON.stringify(profiles[1]).includes('234567890123'));keys.add(profiles[1].verification.documentFrontPath);keys.add(profiles[1].verification.documentBackPath);});
});
