"use client";
import {jobMoney} from "@/lib/worker-jobs";
import Link from "next/link";
import {useWorkerDashboard} from "@/lib/use-job-requests";
import {useVerification,verificationStateLabels} from "@/lib/use-verification";
import {JobRequestCard} from "@/components/job-request-card";
import {WorkerSidebar} from "@/components/worker-sidebar";
import {profileCompletion} from "@/lib/auth";
import {useWorkerServices} from "@/lib/use-worker-services";
import { useAuth } from "@/components/auth-provider";
export default function DashboardPage() {
  const {user, workerProfile, logout} = useAuth();
  const verification = useVerification();
  const verificationLabel=verification.loading?"Loading...":verification.error?"Unavailable":verificationStateLabels[verification.data?.submissionState || "NOT_SUBMITTED"];
  const completion = profileCompletion(user, workerProfile);
  const offerings = useWorkerServices();
  const summary = useWorkerDashboard();
  const jobs = {...summary, requests:summary.data?.previews.requests || []};
  const activeJobs = {...summary, jobs:summary.data?.previews.active || []};
  const allJobs = summary;
  const completedCount = summary.data?.completedJobs || 0;
  return <div className="min-h-screen lg:grid lg:grid-cols-[240px_1fr]">
    <WorkerSidebar/>
    <main id="dashboard" className="min-w-0 px-5 py-8 sm:px-8 lg:px-10"><div className="mx-auto max-w-6xl">
      <p className="text-sm font-semibold text-teal-700">WORKER WORKSPACE</p><h1 className="mt-2 text-3xl font-bold">Welcome, {user?.name}</h1><p className="mt-2 text-slate-600">{workerProfile?.primaryCategory?.name}{workerProfile?.city ? ` - ${workerProfile.city}` : ""}</p><button onClick={logout} className="mt-3 font-semibold text-teal-700">Logout</button><p className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Development preview · New requests use live booking data. Active and completed jobs use live booking data. Gross earnings reflect completed job value; payment settlement is not tracked.</p>
      <section aria-label="Worker summary" className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["requests", "New Requests", jobs.loading ? "..." : jobs.error ? "Unavailable" : String(summary.data?.newRequests ?? 0)], ["active-summary", "Active Jobs", activeJobs.loading ? "..." : activeJobs.error ? "Unavailable" : String(summary.data?.activeJobs ?? 0)], ["completed-summary", "Completed Jobs", allJobs.loading ? "..." : allJobs.error ? "Unavailable" : String(completedCount)], ["earnings", "Today's Earnings", summary.loading ? "..." : summary.error ? "Unavailable" : jobMoney(summary.data?.todayGrossEarnings || "0.00")]].map(([id, label, value]) => <article id={id === "requests" ? undefined : id} key={label} className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-medium text-slate-500">{label}</h2><p className="mt-3 text-3xl font-bold">{value}</p><p className="mt-2 text-xs text-slate-500">{id === "requests" ? "Current requested bookings" : id === "active-summary" ? "Accepted and in-progress bookings" : id === "completed-summary" ? "Completed bookings" : "Gross completed-job value"}</p></article>)}</section>
      <div className="mt-7 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><div className="space-y-6">
        <section id="requests" className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-semibold">New Job Requests</h2><Link href="/job-requests" className="font-semibold text-teal-700">View All Requests</Link></div>{jobs.loading ? <p className="py-8" role="status">Loading job requests...</p> : jobs.error ? <p className="py-8 text-red-700" role="alert">{jobs.error}<button onClick={jobs.reload} className="ml-3 underline">Retry</button></p> : jobs.requests.length ? <div className="mt-5 space-y-4">{jobs.requests.slice(0,3).map(request => <JobRequestCard key={request.bookingNumber} request={request} linkLabel="View Request"/>)}</div> : <div className="py-10 text-center"><p className="font-medium">No new job requests.</p><p className="mt-2 text-sm text-slate-500">New customer booking requests will appear here.</p></div>}</section>
        <section id="jobs" className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-semibold">Active Jobs</h2><Link href="/jobs" className="font-semibold text-teal-700">View All Jobs</Link></div>{activeJobs.loading ? <p className="py-8" role="status">Loading jobs...</p> : activeJobs.error ? <p className="py-8 text-red-700" role="alert">{activeJobs.error}<button onClick={activeJobs.reload} className="ml-3 underline">Retry</button></p> : activeJobs.jobs.length ? <div className="mt-5 space-y-4">{activeJobs.jobs.slice(0,3).map(request => <JobRequestCard key={request.bookingNumber} request={request} job/>)}</div> : <p className="py-10 text-center text-slate-500">No active jobs.</p>}</section>
      </div><div className="space-y-6">
        <section id="profile" className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-semibold">Complete Your Profile</h2><p className="mt-2 text-sm text-teal-700">Basic & professional profile: {completion.percentage}% complete</p><div className="mt-3 flex flex-wrap gap-4 text-sm font-semibold text-teal-700"><Link href="/profile">Edit Profile</Link><Link href="/services">Manage Services</Link><Link href="/availability">Manage Availability</Link></div><p className="mt-2 text-sm leading-6 text-slate-500">Your next steps to get ready for customer requests.</p><ul className="mt-5 divide-y divide-slate-100">{[["basic-information", "Basic Information"], ["professional-profile", "Professional Profile"], ["services", "Services & Pricing"], ["availability", "Availability"], ["verification-check", "Verification"]].map(([id, label]) => <li id={id} key={id} className="flex flex-wrap items-center justify-between gap-2 py-3 text-sm"><span>{label}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-600">{id === "basic-information" ? completion.basic ? "Completed" : "Incomplete" : id === "professional-profile" ? completion.professional ? "Completed" : "Incomplete" : id === "verification-check" ? verificationLabel : id === "services" ? offerings.loading ? "Loading..." : offerings.error ? "Unable to load" : offerings.services.length ? "Completed" : "Incomplete" : workerProfile?.isAvailable ? "Available" : "Unavailable"}</span></li>)}</ul>{offerings.error && <p role="alert" className="mt-4 text-sm text-red-700">{offerings.error}<button onClick={offerings.reload} className="ml-3">Retry</button></p>}</section>
        <section id="verification" className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-semibold">Verification Status</h2><p className="mt-4 inline-block rounded-full bg-amber-50 px-3 py-1 text-sm font-semibold text-amber-800">{verificationLabel}</p><Link href="/verification" className="mt-4 block font-semibold text-teal-700">{verification.data?.submissionState === "NOT_SUBMITTED" ? "Complete Verification" : verification.data?.submissionState === "REJECTED" ? "Resubmit Verification" : "View Verification"}</Link>{verification.error && <p role="alert" className="mt-3 text-red-700">{verification.error}<button onClick={verification.reload} className="ml-3 underline">Retry</button></p>}</section>
      </div></div>
    </div></main>
  </div>;
}
