"use client";
import Link from "next/link";
import {useState} from "react";
import {WorkerSidebar} from "@/components/worker-sidebar";
import {useResource} from "@/lib/use-job-requests";
import {jobMoney,jobTimestamp} from "@/lib/worker-jobs";
type Summary={totalGrossEarnings:string;todayGrossEarnings:string;monthGrossEarnings:string;completedJobs:number;timezone:string};
type History={earnings:{bookingNumber:string;service:{name:string};customer:{name:string};bookingPrice:string;completedAt:string|null}[];pagination:{page:number;limit:number;total:number;totalPages:number}};
export default function EarningsPage() {
  const [page,setPage]=useState(1);
  const summary=useResource<Summary>("/api/worker/earnings/summary");
  const history=useResource<History>(`/api/worker/earnings?page=${page}&limit=20`);
  function refresh(){setPage(1);summary.reload();history.reload();}
  const values=summary.data;
  return <div className="min-h-screen lg:grid lg:grid-cols-[240px_1fr]"><WorkerSidebar/><main className="min-w-0 px-5 py-8 sm:px-8"><div className="mx-auto max-w-6xl"><h1 className="text-3xl font-bold">Earnings</h1><p className="mt-2 text-slate-600">Track the value of your completed jobs.</p><p className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Gross completed-job value. These amounts do not confirm payment received or payout.</p><button onClick={refresh} disabled={summary.loading || history.loading} className="mt-4 font-semibold text-teal-700 disabled:opacity-50">Refresh Earnings</button>
    {summary.loading ? <p role="status" className="mt-6">Loading earnings...</p> : summary.error ? <p role="alert" className="mt-6 text-red-700">{summary.error}<button onClick={summary.reload} className="ml-3 underline">Retry summary</button></p> : values && <><p className="mt-4 text-sm text-slate-500">Completion dates use {values.timezone}.</p><section aria-label="Earnings summary" className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total Gross Earnings",jobMoney(values.totalGrossEarnings)],["Today's Gross Earnings",jobMoney(values.todayGrossEarnings)],["This Month",jobMoney(values.monthGrossEarnings)],["Completed Jobs",String(values.completedJobs)]].map(([label,value])=><article key={label} className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm text-slate-500">{label}</h2><p className="mt-3 text-3xl font-bold">{value}</p></article>)}</section></>}
    <section className="mt-8"><h2 className="text-xl font-semibold">Earnings History</h2>{history.loading ? <p role="status" className="mt-6">Loading earnings...</p> : history.error ? <p role="alert" className="mt-6 text-red-700">{history.error}<button onClick={history.reload} className="ml-3 underline">Retry history</button></p> : history.data?.earnings.length ? <div className="mt-5 grid gap-4 md:grid-cols-2">{history.data.earnings.map(entry=><article key={entry.bookingNumber} className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">Completed: {entry.completedAt ? jobTimestamp(entry.completedAt,values?.timezone || "Asia/Kolkata") : "Completion date not recorded"}</p><Link href={`/jobs/${encodeURIComponent(entry.bookingNumber)}`} className="mt-2 block break-all text-sm font-semibold text-teal-700">{entry.bookingNumber}</Link><h3 className="mt-3 font-semibold">{entry.service.name}</h3><p className="mt-2 text-slate-600">{entry.customer.name}</p><p className="mt-3 font-semibold">Job Value: {jobMoney(entry.bookingPrice)}</p><Link href={`/jobs/${encodeURIComponent(entry.bookingNumber)}`} className="mt-4 inline-block font-semibold text-teal-700">View Job</Link></article>)}</div> : <div className="mt-5 rounded-xl border bg-white p-10 text-center"><p className="font-semibold">{page===1?"No earnings yet.":"No earnings on this page."}</p><p className="mt-2 text-slate-500">Your completed jobs will appear here.</p></div>}
    {history.data && (history.data.pagination.total>0 || page>1) && <nav aria-label="Earnings history pages" className="mt-6 flex flex-wrap items-center justify-center gap-4"><button disabled={page===1 || history.loading} onClick={()=>setPage(value=>value-1)} className="rounded-lg border px-4 py-2 disabled:opacity-50">Previous</button><span>Page {page} of {Math.max(1,history.data.pagination.totalPages)}</span><button disabled={page>=history.data.pagination.totalPages || history.loading} onClick={()=>setPage(value=>value+1)} className="rounded-lg border px-4 py-2 disabled:opacity-50">Next</button></nav>}</section>
    </div></main></div>;
}
