import {extname} from "node:path";
﻿import {fileTypeFromBuffer} from "file-type";
import {Prisma} from "../generated/prisma/client.js";
import {getPrismaClient} from "../lib/prisma.js";
import {AuthError} from "../types/auth.types.js";
import {verificationStorage,cleanupVerificationFiles} from "./storage.service.js";
const select={id:true,verificationStatus:true,verificationSubmittedAt:true,verification:{select:{fullLegalName:true,documentType:true,documentNumberLast4:true,documentFrontPath:true,documentBackPath:true,submittedAt:true,reviewedAt:true,rejectionReason:true}}} satisfies Prisma.WorkerProfileSelect;
function database(){const client=getPrismaClient();if(!client)throw new AuthError(503,"Verification is temporarily unavailable.");return client;}
function owned(userId:string){return {userId,user:{role:"WORKER" as const,isActive:true}};}
export function submissionState(status:string,submittedAt:Date|null){return status==="PENDING" ? submittedAt ? "PENDING_REVIEW" : "NOT_SUBMITTED" : status;}
function dto(row:Prisma.WorkerProfileGetPayload<{select:typeof select}>){const v=row.verification;return {status:row.verificationStatus,submissionState:submissionState(row.verificationStatus,row.verificationSubmittedAt),submittedAt:row.verificationSubmittedAt?.toISOString()??null,reviewedAt:v?.reviewedAt?.toISOString()??null,rejectionReason:v?.rejectionReason??null,verification:v?{fullLegalName:v.fullLegalName,documentType:v.documentType,maskedDocumentNumber:"XXXX "+v.documentNumberLast4,documents:{front:!!v.documentFrontPath,back:!!v.documentBackPath},submittedAt:v.submittedAt.toISOString()}:null};}
export async function getVerification(userId:string){const row=await database().workerProfile.findFirst({where:owned(userId),select});if(!row)throw new AuthError(404,"Worker profile not found");return dto(row);}
function allowed(row:Prisma.WorkerProfileGetPayload<{select:typeof select}>){if(row.verificationStatus==="PENDING"&&row.verificationSubmittedAt)throw new AuthError(409,"Your verification is already under review.");if(row.verificationStatus==="VERIFIED")throw new AuthError(409,"Verified workers cannot replace verification documents.");if(row.verificationStatus==="SUSPENDED")throw new AuthError(403,"Suspended verification cannot be resubmitted.");}
export function validateVerification(body:unknown){if(!body||typeof body!=="object"||Array.isArray(body))throw new AuthError(400,"Invalid verification details.");const input=body as Record<string,unknown>;if(Object.keys(input).some(key=>!["fullLegalName","documentType","documentNumber"].includes(key)))throw new AuthError(400,"Unsupported verification field.");if(typeof input.fullLegalName!=="string"||input.fullLegalName.trim().length<2||input.fullLegalName.trim().length>100)throw new AuthError(400,"Legal name must contain 2 to 100 characters.");const types={AADHAAR:/^[2-9]\d{11}$/,PAN:/^[A-Z]{5}\d{4}[A-Z]$/,DRIVING_LICENSE:/^[A-Z]{2}\d{13}$/,VOTER_ID:/^[A-Z]{3}\d{7}$/};if(typeof input.documentType!=="string"||!Object.hasOwn(types,input.documentType)||typeof input.documentNumber!=="string"||input.documentNumber.length>40)throw new AuthError(400,"Select a supported identity document and enter its number.");const type=input.documentType as keyof typeof types;const number=input.documentNumber.trim().toUpperCase().replace(/[ -]/g,"");if(!types[type].test(number))throw new AuthError(400,"Enter a valid number for the selected document type.");return {fullLegalName:input.fullLegalName.trim(),documentType:type,documentNumberLast4:number.slice(-4)};}
async function inspect(file:Express.Multer.File){if(!file.size||file.size>5*1024*1024)throw new AuthError(400,"Each document must be no larger than 5 MB.");if(![".jpg",".jpeg",".png",".pdf"].includes(extname(file.originalname).toLowerCase()))throw new AuthError(400,"Upload JPG, PNG or PDF documents only.");const detected=await fileTypeFromBuffer(file.buffer).catch(()=>undefined);if(!detected||!["image/jpeg","image/png","application/pdf"].includes(detected.mime)||file.mimetype!==detected.mime)throw new AuthError(400,"Upload valid JPG, PNG or PDF documents.");return detected.ext==="jpg"?"jpg":detected.ext==="png"?"png":"pdf";}
export async function submitVerification(userId:string,body:unknown,files:Record<string,Express.Multer.File[]>){const input=validateVerification(body);const current=await database().workerProfile.findFirst({where:owned(userId),select});if(!current)throw new AuthError(404,"Worker profile not found");allowed(current);if(!files.documentFront?.[0]||Object.keys(files).some(key=>!["documentFront","documentBack"].includes(key)))throw new AuthError(400,"A front identity document is required.");if(input.documentType!=="PAN"&&!files.documentBack?.[0])throw new AuthError(400,"A back identity document is required for this document type.");const front=files.documentFront[0],back=files.documentBack?.[0];const frontType=await inspect(front),backType=back?await inspect(back):null;const saved:string[]=[];let result;
 try{saved.push(await verificationStorage.save(front.buffer,frontType));if(back&&backType)saved.push(await verificationStorage.save(back.buffer,backType));const submittedAt=new Date();result=await database().$transaction(async tx=>{
  // Conditional UPDATE locks this profile. Only one first/rejected submission wins.
  const changed=await tx.workerProfile.updateMany({where:{...owned(userId),id:current.id,verificationStatus:current.verificationStatus,verificationSubmittedAt:current.verificationSubmittedAt},data:{verificationStatus:"PENDING",verificationSubmittedAt:submittedAt}});if(changed.count!==1)throw new AuthError(409,"Your verification has changed. Refresh and try again.");
  const data={...input,documentFrontPath:saved[0]!,documentBackPath:saved[1]??null,submittedAt,reviewedAt:null,rejectionReason:null};await tx.workerVerification.upsert({where:{workerId:current.id},create:{workerId:current.id,...data},update:data});const updated=await tx.workerProfile.findFirst({where:owned(userId),select});if(!updated)throw new AuthError(404,"Worker profile not found");return dto(updated);
 });}catch(error){await cleanupVerificationFiles(saved);throw error;}await cleanupVerificationFiles([current.verification?.documentFrontPath,current.verification?.documentBackPath]);return result;
}
