import { Router } from "express";
import { authenticate, authorizeRoles } from "../middleware/auth.middleware.js";
import * as controller from "../controllers/address.controller.js";
const router = Router();
router.use(authenticate, authorizeRoles("CUSTOMER"));
router.get("/", controller.list);
router.post("/", controller.create);
router.patch("/:id/default", controller.setDefault);
router.patch("/:id", controller.update);
router.delete("/:id", controller.remove);
export default router;
