"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { CustomerNav } from "../../customer-nav";
import { useMarketplace } from "@/lib/use-marketplace";
import { money, profession, type WorkerDetail } from "@/lib/marketplace";
export default function WorkerProfilePage() {
 const { id } = useParams<{ id: string }>();
 const { data, loading, error, status, retry } = useMarketplace<{ worker: WorkerDetail }>(`/api/workers/${encodeURIComponent(id)}`);
 const worker = data?.worker;
 return <div className="min-h-screen bg-gray-50 text-gray-900"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-4 py-5 sm:px-6"><Link href="/" className="text-2xl font-bold text-blue-600">WorkerBooking</Link><CustomerNav /></div></header><main className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><Link href="/workers" className="text-sm text-blue-600">{"\u2190"} Back to Workers</Link>
 {loading ? <p role="status" className="mt-8">Loading worker profile...</p> : error ? <section className="mt-6 rounded-2xl border bg-white p-8"><h1 className="text-2xl font-bold">{status === 404 ? "Worker not found" : "Unable to load worker profile"}</h1>{status !== 404 && <><p role="alert" className="mt-3">{error}</p><button onClick={retry} className="mt-4 text-blue-600">Retry</button></>}</section> : worker && <>
 <section className="mt-6 flex flex-wrap items-center gap-6 rounded-2xl border bg-white p-6 sm:p-8"><div aria-hidden="true" className="flex h-24 w-24 items-center justify-center rounded-full bg-blue-100 text-3xl font-bold text-blue-700">{worker.name.split(" ").map(part=>part[0]).slice(0,2).join("")}</div><div className="flex-1"><h1 className="text-3xl font-bold">{worker.name}</h1><p className="mt-2 text-gray-600">{profession(worker)}</p><p className="mt-3">{"\u2B50"} {worker.rating} ({worker.totalReviews} reviews)</p><p className="mt-2">{worker.experienceYears} years experience</p><p className={`mt-3 inline-block rounded-full px-3 py-1 text-sm ${worker.isAvailable ? "bg-green-100 text-green-800" : "bg-red-100 text-red-800"}`}>{worker.isAvailable ? "Available" : "Currently Unavailable"}</p></div><div><p className="font-semibold">Starting from {money(worker.startingPrice)}</p>{worker.isAvailable ? <Link href={`/booking?workerId=${worker.id}`} className="mt-4 block rounded-lg bg-blue-600 px-6 py-3 text-center font-semibold text-white">Book Now</Link> : <button disabled className="mt-4 rounded-lg bg-gray-200 px-6 py-3 text-gray-500">Currently Unavailable</button>}</div></section>
 <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">About Worker</h2><p className="mt-4 text-gray-600">{worker.bio || "No description provided."}</p></section><section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Availability</h2><p className="mt-4">{worker.isAvailable ? "Available for booking" : "Currently unavailable"}</p></section></div>
 <section className="mt-6 rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Services & Pricing</h2><div className="mt-4 divide-y">{worker.services.map(service=><div key={service.id} className="flex flex-wrap justify-between gap-4 py-4"><div><h3 className="font-medium">{service.name}</h3><p className="text-sm text-gray-500">{service.category.name}</p></div><p className="font-semibold">{money(service.price)}</p></div>)}</div></section>
 <section className="mt-6 rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Customer Reviews</h2>{worker.reviews.length ? worker.reviews.map(review=><article key={review.id} className="mt-5 border-t pt-4"><h3 className="font-medium">{review.customerName}</h3><p className="mt-1 text-amber-600">{review.rating} / 5 stars</p>{review.comment && <p className="mt-2 text-gray-600">{review.comment}</p>}<p className="mt-2 text-xs text-gray-500">{new Date(review.createdAt).toLocaleDateString("en-IN")}</p></article>) : <p className="mt-4 text-gray-500">No reviews yet.</p>}</section>
 </>}
 </main></div>;
}
